### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by tugcekeser** [IOSPartyPlanner/PartyPlanner#23]
- Need "Add volunteer" api for adding volunteer to tasks
- Need "Remove volunteer" api for removing volunteer from tasks
- Need to get host profile image in fetchEvents function in HomeViewController
- After added a task in TasksViewController, previous tasks are duplicating. (Bug)
- Firebase media storage API

**Comment by una-020** [comment]
This has been fixed. Duplication issue is being looking into by Bharath in a different issue. Closing this.
