### ISSUE TITLE
Guest's post events not showing

### ISSUE THREAD

**Issue by billyean** [IOSPartyPlanner/PartyPlanner#41]
Guest was in guestEmailList but it's now showing in home page

**Comment by tugcekeser** [comment]
upcomingeventsbyUserEmail and pastEventsbyUserEmail API's are not working. Could you check it ?

**Comment by billyean** [comment]
Fix by https://github.com/IOSPartyPlanner/PartyPlanner/commit/c8cbe64aa62c6a11f63910bde5503de491770446
