### ISSUE TITLE
Hardcoded dates to be changed in homeviewcontroller

### ISSUE THREAD

**Issue by una-020** [IOSPartyPlanner/PartyPlanner#48]
All the event dates are getting displayed as "May19"

**Comment by una-020** [comment]
for your reference. 
![screen shot 2017-05-15 at 8 25 24 pm](https://cloud.githubusercontent.com/assets/18301605/26088571/c78168d4-39ac-11e7-846a-a68d21b21cdb.png)

**Comment by tugcekeser** [comment]
Solved
