### ISSUE TITLE
User screen to display upcoming and past events 

### ISSUE THREAD

**Issue by bharathdn** [IOSPartyPlanner/PartyPlanner#6]
User screen to display upcoming and past events.

user should be able to switch between the events hosted by the user and the events the user is invited to.

A list presentation would be ideal. Each item in the list contains at least the following details:

- Event Name
- Host
- Event Date or time left for the event to start (such as: 02-mar-2018, or 2 days to go, or starting in 5 hours)
- A Map icon that will show the event location on map when clicked
- Event image and host image
- Users RSVP info for that event

**Comment by billyean** [comment]
I guess this should be done by home screen, assign to Rabia

**Comment by bharathdn** [comment]
Closing issue as implementation is complete
